platform :ios, '9.0'
use_frameworks!

target 'POWImageGallery_Example' do
  pod 'POWImageGallery', :path => '../'
  pod 'SDWebImage', '~> 4.2'
end

target 'POWImageGallery_Tests' do
    pod 'POWImageGallery', :path => '../'
    pod 'SDWebImage', '~> 4.2'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
end

